### ISSUE TITLE
Any support for Opennebula 5+? 

### ISSUE THREAD

**Issue by thebrooder** [blackberry/chef-provisioning-opennebula#11]
The Gem dependencies for version 0.4.8 of the chef-provisioning-opennebula gem list opennebula < 5.    Is there any support for more recent Opennebula releases greater than 5 (we have recently upgrade to 5.2.1)?  

We have tried provisioning with older versions (4.14.2) of the opennebula gem but generate a gem dependency error.

Gem::MissingSpecVersionError
    ----------------------------
    Could not find 'opennebula' (~> 5.2.1) - did find: [opennebula-4.14.2]

Running with opennebula gem 5.2.1 generates a different error:

NameError
    ---------
    uninitialized constant OpenNebula::Document

**Comment by bbuczynski** [comment]
FYI ... this was open sourced by BlackBerry and a lot of things have changed at BlackBerry since this was released.  One of those things is that I am no longer with the company; I wrote 90%+ of the initial code.  I would be more than happy to update the driver if I had access to OpenNebula 5+.  Right now I can't tell you when or if there would be an update to support OpenNebula 5+, because I am no longer with the company.  To be on the safe side I'd say "You're on your own", but feel free to contact me if you have any questions.

**Comment by danfromtitan** [comment]
@thebrooder  - Opennebula 5.x is supported (and tested) with version 0.4.9 of the gem. It also provides backwards compatibility with ONE <5.
There is a known issue with the driver when running chef provisioning against different ONE versions in the same recipe, the driver tries to overload a new opennebula gem version and it's denied by the ruby kernel. This can happen mostly in an upgrade scenario where you run multiple versions of Opennebula in different environments. I'm working on a fix soon to be released.
